### ISSUE TITLE
Expanding the menu button is pushing the contents out of the main window

### ISSUE THREAD

**Issue by UnresolvedCold** [sum1275/myapp#1]
Right now the main content is being pushed out of the screen after expanding the menu items. 
The default behavior should have been to rescale the content to fit the page width. 
Please look into this. An attachment of the same is attached herewith. 
![Issue1](https://user-images.githubusercontent.com/35415266/180169539-b5c37b55-1e3b-428b-8b6a-76869d20e99d.png)

**Comment by sum1275** [comment]
Header Issue fixed.

**Comment by UnresolvedCold** [comment]
Now it's not scalable. Its width is fixed. Can you look into this?

**Comment by sum1275** [comment]
Yes checking into the sidebar issue Scalability.

**Comment by UnresolvedCold** [comment]
https://github.com/sum1275/myapp/pull/2

**Comment by sum1275** [comment]
😀
